FROM ghcr.io/smallgamecz/smallgamecz/node15110:15.11.0-alpine3.13
LABEL MAINTAINER="Daniel Rataj <daniel.rataj@centrum.cz>"

RUN apk add --no-cache openssl=1.1.1s-r0 git=2.30.6-r0 \
  && rm -rf /var/cache/apk/*

WORKDIR /app

COPY api/package.json .

# copy required app files
COPY api/api ./api
COPY api/config/ ./config
COPY api/static/ ./static
COPY api/test/ ./test
COPY api/app.js ./app.js
COPY api/.sailsrc ./.sailsrc

RUN npm install --quiet

# start Sails app
CMD [ "npm", "start" ]

# expose port for Node
EXPOSE 1337
