FROM ghcr.io/smallgamecz/smallgamecz/node14160:14.16.0-alpine3.13
LABEL MAINTAINER="Daniel Rataj <daniel.rataj@centrum.cz>"

# set a working directory
WORKDIR /app

# copy source code to WORKDIR
COPY panel/ .

# install quasar globally
RUN yarn global add @quasar/cli@1.1.3

# install dependencies
RUN yarn install

COPY panel/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

# expose port for Node server
EXPOSE 80
